### ISSUE TITLE
Address errors in BNS and NGRT jobs

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs#26]
Once the bulk load is complete for `bns/survey.js`, `bns/price.js`, `ngrt/2017.js` and `ngrt2019.js` we'll need to:

- [x] analyze all errors from the 10k submissions and determine which require changes to the jobs, adaptors, or postgres DB configuration
- [x] make those changes
- [x] re-processes messages received with failed run-states or no matching run-states from September 20-22.

## Getting Started:
1. Check out the runs page: https://openfn.org/projects/1168/runs
2. There are 570 failures and 173 timeouts. (Taylor is looking into the timeouts, please inspect the failures.)
3. https://analytics.openfn.org/question/276 - Is set to display all the relevant errors, and picks out row 15 of the logs. In about 85% of the rows, row 15 includes this "T07 already declared" error.
4. Other errors include "RequestError: Incorrect syntax near 'frais'." or "RequestError: Incorrect syntax near 'bénéficié'.", etc.
5. For all of the errors, you can download this report and view the logs locally, or click into the runs to attempt to reproduce the errors on production or on your local machine. The jobs are idempotent, so we simply need to get them working eventually.
6. Once you have determined and made the changes required to either the job, the adaptor, or the db, @taylordowns2000 can handle the bulk-reprocessing.

**Comment by taylordowns2000** [comment]
Update! I've found the timeout issue—a problem with `language-mssql` not catching errors and closing the client. Addressing now.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , @lakhassane , if Jonathan thinks "already declared" is related to timing, we might be able to address this with the concurrency work I hope to do on `platform` today. I've now set their concurrency to 1 manually, so let's see if any new errors like that one appear after `2020-09-23 09:25:00 GMT`

**Comment by taylordowns2000** [comment]
Re-bulked the changed job (Jonathan switched the tag) and they finished before `2020-09-24 17:20:00 GMT`.
Ordered all 12k+ submissions (some duplication early and the redundancy is good) after `2020-09-24 17:22:00 GMT`.

**Comment by taylordowns2000** [comment]
All messages in a successful state. Closing
